### ISSUE TITLE
Alarm triggered

### ISSUE THREAD

**Issue by ojoaosemtil** [EHylands/homebridge-qolsys#26] opened 2023-10-22 00:58 UTC
Hello,
I noticed that HomeKit only notifies me of the alarm triggered if I use the panic on the panel - which as options for police, fire and medical emergency.

If I open a door or move with home ou away mode activated, HomeKit doesn’t notify me about the alarm being triggered.

Is it normal behavior?

**Comment by EHylands** [comment] 2023-10-22 01:10
Hi,
I unfortunately can’t reproduce the issue since I’m only running the panel without any sensors.

Could you:
- Enable “Show Qolsys Panel debug information” in config file
- Run Homebridge in debug mode with -D flag
- Submit log file with any panel activity while a sensor triggers the alarm

It would be an issue if the alarm is reported in log file but not in Homekit

**Comment by ojoaosemtil** [comment] 2023-10-22 01:12
Ok, I’ve been troubleshooting some issues with my alarm system, maybe tomorrow I’ll be able to do it!

**Comment by cistearns** [comment] 2023-10-22 01:27
I think what you are running into is the difference between the panel actually being in an alarm state, and the panel giving you a warning and delay before it goes into alarm. The panel internally doesn't go into a true alarm state until the point that it will call the central station.
When you trigger a panic alarm, the panel will immediately go into an alarm state and dispatch to the central monitoring station.  When you open a door while the panel is armed, it first goes into entry delay, this isn't an alarm state and the panel won't broadcast that is happening. This is to give you time to disarm. If you fully wait for the entire entry delay to pass then the panel will enter alarm state at which point it should broadcast that it is in alarm state and start blaring the its siren.

This is important behavior to prevent false alarms to the central monitoring station. I assume you probably aren't paying for monitoring, so if you want to change this behavior you can reduce the entry delay or use instant trip zone types, though it means your panel and any sirens will start blaring once you do. Instant trip away zones are typically only used on sensors that wouldn't be activated by entry.  Its worth noting though that some of the instant trip zones are defined as only instant IF an entry delay zone wasn't tripped first - this is a common setting for motion zones.

**Comment by ojoaosemtil** [comment] 2023-10-22 01:32
Yes I understand the delays, I’m really talking about the panel going into alarm state, only trigger in HomeKit if I trigger panic alarm.

I’m paying for monitoring that’s why I can’t troubleshoot it right now ahah

**Comment by ojoaosemtil** [comment] 2023-10-28 00:05
I was testing right now the alarm and I forgot to enable debug mode, but, I have this on the log:

[28/10/2023, 00:52:31] [homebridge-qolsys] Zone3(Porta de Entrada): OPEN
[28/10/2023, 00:52:31] [homebridge-qolsys] Partition0(SYSTEM): ENTRY_DELAY
[28/10/2023, 00:52:34] [homebridge-qolsys] Zone3(Porta de Entrada): CLOSED
**[28/10/2023, 00:52:41] [homebridge-qolsys] Received Invalid Arming Type (Received Invalid Alarm Type:{"event":"ALARM","alarm_type":"","version":1,"partition_id":0,"requestID":"59c112ba-0984-476b-a1ae-42303bbf16e5"})**
[28/10/2023, 00:52:45] [homebridge-qolsys] Partition0(SYSTEM): DISARM

Seems like it doesn't recognize Alarm trigger, it says its an invalid Arming Type...

**Comment by EHylands** [comment] 2023-10-28 00:47
Interesting error !

Please take note that Qolsys Control 4 interface is mostly undocumented.
alarm_type":"" has not been reported before by Homebridge or HomeAssistant users.
Normally, alarm_type":"AUXILIARY", alarm_type":"FIRE" or alarm_type":"POLICE" is reported by panel.

@cistearns I suggest mapping alarm_type":"" to alarm_type":"POLICE" to fix issue and trigger alarm in HomeKit.

**Comment by EHylands** [comment] 2023-10-28 01:23
@ojoaosemtil : It should now trigger an alarm in alternate version v0.4.1-beta.0

**Comment by cistearns** [comment] 2023-10-28 01:24
@EHylands baring other info, that seems like a reasonable approach.

@ojoaosemtil what panel software version are you on, and what zone type was configured for the zone that tripped and caused the alarm?

**Comment by EHylands** [comment] 2023-10-28 01:33
> @EHylands baring other info, that seems like a reasonable approach.
> 
> @ojoaosemtil what panel software version are you on, and what zone type was configured for the zone that tripped and caused the alarm?

Do you think it has something to do with 'Dialer Delay' and that a full alarm_type="POLICE" would be triggered after timer expiration ?

**Comment by ojoaosemtil** [comment] 2023-10-28 01:36
It says Partition0 (SYSTEM) and Zone3
My dialer delay is disabled, previously it had a 5 seconds delay, but not anymore.

**Comment by EHylands** [comment] 2023-10-28 01:40
Out of curiosity, which group name are you using for door and motion sensors ?

![image](https://github.com/EHylands/homebridge-qolsys/assets/90003064/29388445-99bc-4f70-bc8c-5d04b131c0f1)

**Comment by cistearns** [comment] 2023-10-28 01:45
@ojoaosemtil From the configuration for ZONE 3, what Sensor Type and more importantly what Sensor Group do you have it set as (something like 10 Entry-Exit Normal Delay).
Also what language do you have set for the panels default language? This along with the firmware version might give us some added clues.

@EHylands the reason I'm cautious about this as a fix is, if something about this panel is such that it outputs all alarms with no type. Id want to be clear with users of this extension in those cases that alarms like Fire and Flood may also be mapped to Police. The other thing I'm cautious about is accidentally emitting silent/duress type alarms to HomeKit in a way that it performs actions it shouldn't that might endanger someone in a duress situation. This still might be the best option, but knowing the conditions this is happening in would at least let us document it so that people know what to expect.

**Comment by EHylands** [comment] 2023-10-28 01:54
> @ojoaosemtil From the configuration for ZONE 3, what Sensor Type and more importantly what Sensor Group do you have it set as (something like 10 Entry-Exit Normal Delay).
> 
> Also what language do you have set for the panels default language? This along with the firmware version might give us some added clues.
> 
> 
> 
> @EHylands the reason I'm cautious about this as a fix is, if something about this panel is such that it outputs all alarms with no type. Id want to be clear with users of this extension in those cases that alarms like Fire and Flood may also be mapped to Police. The other thing I'm cautious about is accidentally emitting silent/duress type alarms to HomeKit in a way that it performs actions it shouldn't that might endanger someone in a duress situation. This still might be the best option, but knowing the conditions this is happening in would at least let us document it so that people know what to expect.
> 
> 

Totally agree about implications for a silent alarm.

For other situations, HomeKit doesn't discriminate between fire, police or aux alarm. User impact would be minimal. Only Homebridge log file would be affected.

I agree we need to get more information about sensor group. HomeAssistant user base is fairly bigger than Homebridge and an empty alarm type has not been reported yet.

**Comment by ojoaosemtil** [comment] 2023-10-28 12:42
So, my panel is on version 4.3.0
It is in Portuguese
Door and window sensor is on group 10 - entry-exit-normal delay
Motion sensors are on group 17 - Away-Instant Motion
![IMG_2863](https://github.com/EHylands/homebridge-qolsys/assets/49502020/923b0f4c-30c2-4fb9-9973-9bcffe856fad)
![IMG_2862](https://github.com/EHylands/homebridge-qolsys/assets/49502020/d19deab7-02c9-4295-aae4-5afcb57011bf)

**Comment by ojoaosemtil** [comment] 2023-11-25 16:22
Just an update.
I’m on the latest beta and my alarm triggered, away mode and door opened, and HomeKit didn’t recognized it, no HomePod sound or notification from home app

**Comment by EHylands** [comment] 2023-11-25 16:43
> Just an update. I’m on the latest beta and my alarm triggered, away mode and door opened, and HomeKit didn’t recognized it, no HomePod sound or notification from home app

Hi, 
lastest beta only contained fix to add heat sensors
I just merged both betas in v0.4.1.
Should work as expected with latest version.

**Comment by ojoaosemtil** [comment] 2023-11-25 16:45
Ok I’ll update and see how it reacts next time

**Comment by cistearns** [comment] 2023-11-29 01:24
Just to circle back here, one difference of note is that it looks like this panel is using PowerG sensors. These are less common in generic North America installs since they are more expensive. So this may be a JCI bug with those sensors. Would need someone else with PowerG sensors to confirm.

**Comment by cistearns** [comment] 2024-02-07 04:46
@ojoaosemtil have you had the opportunity to confirm if the changes in 0.4.1 or later have resolved your issue?

**Comment by ojoaosemtil** [comment] 2024-02-07 11:25
Not yet, maybe this week I’ll try it.

**Comment by cistearns** [comment] 2024-02-15 16:38
@ojoaosemtil I'm going to go ahead and close out the issue. If you still experience a bug please feel free to re-open this and provide any new information for the plugin logs that would help resolve it.

**Closed by cistearns** 2024-02-15 16:38 UTC
Labels: bug

**Comment by ojoaosemtil** [comment] 2024-04-05 11:04
Testes today, it’s working as it should right now! Thank you!
