### ISSUE TITLE
Support for the IQ Pro

### ISSUE THREAD

**Issue by smacgregor** [EHylands/homebridge-qolsys#30] opened 2023-11-21 16:25 UTC
I'm considering an IQ Pro instead of a IQ Panel 4 and was wondering if this homebridge plugin will have pending support for the Pro. I see the Hub is marked as support pending already.

Thanks!

**Comment by EHylands** [comment] 2023-11-22 00:04
> I'm considering an IQ Pro instead of a IQ Panel 4 and was wondering if this homebridge plugin will have pending support for the Pro. I see the Hub is marked as support pending already.
> 
> 
> 
> Thanks! 

Hi,
I wrote ´status pending' for IQ4 Hub because no one reported using it with the plugin yet ...

In spec, it's stated that Control4 is still an integration partner for IQ pro, but I can't find any procedure in installation guide to enable the feature. The Control4 integration has been fairly consistent between all supported panels and official driver hasn't been updated in a long time. IQ pro might work with this plugin, but don't take this for granted...

**Comment by smacgregor** [comment] 2023-11-22 02:47
Thanks for the info @EHylands - if I do go with the Pro over the IQ 4 I will be a guinea pig and see if i can find the ability to enable Control4!

**Comment by EHylands** [comment] 2023-11-22 02:50
> Thanks for the info @EHylands - if I do go with the Pro over the IQ 4 I will be a guinea pig and see if i can find the ability to enable Control4!

The Pro panel looks line a really nice product!
Please report back to us if you can get it to work with the plugin (or with log file if you need us to debug anything!)

**Comment by cistearns** [comment] 2023-11-22 04:58
Both the IQ Pro and the IQ 4 NS are programmed using a Qolsys mobile app so it is going to depend on what they expose in the app.

**Comment by cistearns** [comment] 2024-02-07 04:38
@smacgregor can you confirm that you got the plugin running against the IQ Pro?

**Comment by cistearns** [comment] 2024-02-14 01:08
Closing for now under the unconfirmed assumption that the plugin does work against the IQ Pro, when the IQ Installer app is used to configure Control4 support the same as an IQ4.

**Closed** 2024-02-14 01:08 UTC
